# To execute this docker-compose yml file use `docker-compose up`
# Add the `-d` flag at the end for detached execution

version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-20210930
    shm_size: 2gb
    depends_on:
      - selenium-hub
    scale: 2
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    ports:
      - "5900"

  firefox:
    image: selenium/node-firefox:4.0.0-rc-2-20210930
    shm_size: 2gb
    depends_on:
      - selenium-hub
    scale: 2
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    ports:
      - "5900"

  selenium-hub:
    image: selenium/hub:4.0.0-rc-2-20210930
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"